
package edu.bcm.dldcc.big.nursa.dkcoin12.soap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "dkcoin", targetNamespace = "urn:dkcoin", wsdlLocation = "http://staging.dkcoin.org/service/wsdl")
public class Dkcoin
    extends Service
{

    private final static URL DKCOIN_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.bcm.dldcc.big.nursa.dkcoin12.soap.Dkcoin.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.bcm.dldcc.big.nursa.dkcoin12.soap.Dkcoin.class.getResource(".");
            url = new URL(baseUrl, "http://staging.dkcoin.org/service/wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://staging.dkcoin.org/service/wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DKCOIN_WSDL_LOCATION = url;
    }

    public Dkcoin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dkcoin() {
        super(DKCOIN_WSDL_LOCATION, new QName("urn:dkcoin", "dkcoin"));
    }

    /**
     * 
     * @return
     *     returns DkcoinPortType
     */
    @WebEndpoint(name = "dkcoinPort")
    public DkcoinPortType getDkcoinPort() {
        return super.getPort(new QName("urn:dkcoin", "dkcoinPort"), DkcoinPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DkcoinPortType
     */
    @WebEndpoint(name = "dkcoinPort")
    public DkcoinPortType getDkcoinPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:dkcoin", "dkcoinPort"), DkcoinPortType.class, features);
    }

}
